game:
    time: 60
    friendly-fire: false
    human-respawn: 5
    zombie-respawn: 5

team:
    zombie:
    
    human:

    waiting:
    
spawn:
    zombie:
    
    human:
    
    zombiehold:
    
    humanhold:
    
    leave:
    
    wait:
    
loadout:
    zombie:
    
    human:
    
potion:
    zombie:
    
    human:
    
